name: Build and Run emulator

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Setup Xvfb
        uses: coactions/setup-xvfb@v1
        with:
          run: python .venv/window_file_input.py "user_1" "computer_1" ".venv/files.tar" ".venv/json.log" 
      - name: Check accurancy
        run: |
          diff expected_output.txt output.txt || echo "Output does not match expected results!"
