name: Build and Run emulator

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Run window.py
        run: |
          python window.py "user_1" "computer_1" "ShellEmulator/.venv/files.tar" "ShellEmulator/.venv/json.log" 
